@user = doe
@password = 12345678
@id=24

GET https://httpbin.org/basic-auth/{{user}}/{{password}}
Authorization: Basic {{user}}{{password}}



GET http://localhost:3000/


GET http://localhost:3000/contextserver/get-route